# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='thumbs/%Y/%m/%d')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='album.Album')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
